"""create project class

Revision ID: 56de4af8efcf
Revises: 
Create Date: 2023-08-17 09:01:06.596266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56de4af8efcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
